const TEMP_FOLDER = 'temp';

const FILE_WITH_GET_ERRORS = 'errorsWithGet.xlsx';
const FILE_WITH_GET_ERRORS_WP = 'errorsWithGetWp.xlsx';

const FOLDER_WITH_BOOK_LINKS = 'book_links';
const FOLDER_WITH_BOOK_LINKS_CLEANED = 'book_links--cleaned';
const FOLDER_WITH_BOOK_DATA = 'book_data';
const FOLDER_WITH_BOOK_DATA_PUBLIC = 'book_data_public';
const FOLDER_WITH_SERIES_LINKS = 'series_links';
const FOLDER_WITH_SERIES_DATA = 'series_data';
const FOLDER_WITH_BOOK_COVERS = 'book_covers';
const FOLDER_WITH_AUTHOR_IMAGES = 'author_images';
const FOLDER_WITH_BOOK_IMAGES = 'book_images';

const FOLDER_WITH_BOOK_LINKS_WP = 'wp_book_links';
const FOLDER_WITH_BOOK_DATA_WP = 'wp_book_data';
const FOLDER_WITH_BOOK_DATA_PUBLIC_WP = 'wp_book_data_public';

module.exports = {
  TEMP_FOLDER,
  FILE_WITH_GET_ERRORS,
  FILE_WITH_GET_ERRORS_WP,
  FOLDER_WITH_BOOK_LINKS,
  FOLDER_WITH_BOOK_LINKS_CLEANED,
  FOLDER_WITH_BOOK_DATA,
  FOLDER_WITH_BOOK_DATA_PUBLIC,
  FOLDER_WITH_SERIES_LINKS,
  FOLDER_WITH_SERIES_DATA,
  FOLDER_WITH_BOOK_COVERS,
  FOLDER_WITH_AUTHOR_IMAGES,
  FOLDER_WITH_BOOK_IMAGES,
  FOLDER_WITH_BOOK_LINKS_WP,
  FOLDER_WITH_BOOK_DATA_WP,
  FOLDER_WITH_BOOK_DATA_PUBLIC_WP,
};
