const { writeLog } = require('useful-toolbox-js');

function showUsage() {
  writeLog.log(
    'Usage: node book-scraper.js <ACTION> <OPTIONS>\n',
    'Actions:\n',
    '\tget-news: Get book links from the new books\n',
    '\tget-bests: Get book links from the bestsellers\n',
    '\tget-main-cat: Get book links from the main catalogs\n',
    '\tget-all: Get book links from all catalogs\n',
    '\tget-errors: Get book links from the error file\n',
    '\tget <EXCEL FILE>: Get book links from an Excel file (to test or to revisit errors)\n',
    '\n',
    '\tremove-doubles: Remove duplicate book links found with get\n',
    '\n',
    '\tscrape-news: Scrape book data with the new book links\n',
    '\tscrape-bests: Scrape book data with the bestseller links\n',
    '\tscrape-cat <CATALOG NAME>: Scrape book data with links from the given catalog\n',
    '\tscrape-main-cat: Scrape book data with links from the main catalogs\n',
    '\tscrape-all: Scrape book data with links from all catalogs\n',
    '\tscrape-errors: Scrape book data with errors\n',
    '\tscrape-data: Re-scrape book data already found according to the given options\n',
    '\tscrape <EXCEL FILE>: Scrape book data with links from an Excel file (especially to test)\n',
    '\n',
    '\tget-cat: Get the main categories with their subcategories\n',
    '\tclean-covers: Remove covers that are no longer used\n',
    '\tclean-authors: Remove author images that are no longer used\n',
    '\tshow-logs: Show file logs\n',
    '\tshow-errors: Show errors logs\n',
    '\n',
    'Options:\n',
    '\t--only-<MODULES>: Scrape only given modules\n',
    '\t--update: Update book data by going to the websites\n',
    '\t--images: Update the images of books that don\'t have one\n',
    '\t--not-found: Update books that were not found\n',
    '\t--not-load: Do not load existing books (especially to test)\n',
    '\t--save-pages: Save page content to speed up testing\n',
    '\t--use-saved-pages: Use saved pages to speed up testing\n',
    '\n',
    '\t--speed-<milliseconds>: For show-logs, configure the log interval\n',
    '\t--open: Open the browser (by default)\n',
    '\t--hide: Hide the browser (not recommended)\n',
    '\t--dev: Display dev logs\n',
    '\t--debug: Display debug logs that are not linked to a module\n',
    '\t--debug-<MODULES>: Display debug logs of the given modules\n',
    '\t--debug-all: Display all debug logs\n',
    '\n',
    'Modules:\n',
    '\tll\n',
    '\taa\n',
    '\tar\n',
    '\trc\n',
  );
}

module.exports = showUsage;
